# Generated by Django 5.1.6 on 2025-02-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('update_dt',)},
        ),
    ]
